# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2

job_defaults: &defaults
    docker:
      - image: circleci/clojure:tools-deps
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m      
      ENVIRONMENT: "test"

jobs:
  build:
    <<: *defaults
    # Download and cache dependencies
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Clojure setup
          command: clojure -R:cljtest -e "(println \"Clojure setup done\")"
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}

  test-clj:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "deps.edn" }}
      - run: 
          name: Run tests
          command: clojure -A:cljtest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-clj:
          requires:
            - build
